"""authoritative schema baseline

Revision ID: bc8fe52aaace
Revises: phase2_filter_indexes
Create Date: 2026-03-18 22:57:57.806486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc8fe52aaace'
down_revision: Union[str, Sequence[str], None] = 'phase2_filter_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_rule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('scope', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('rfq',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('client', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('rfq_code', sa.String(length=20), nullable=True),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_stage_id', sa.UUID(), nullable=True),
    sa.Column('outcome_reason', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfq_client'), 'rfq', ['client'], unique=False)
    op.create_index(op.f('ix_rfq_created_at'), 'rfq', ['created_at'], unique=False)
    op.create_index(op.f('ix_rfq_current_stage_id'), 'rfq', ['current_stage_id'], unique=False)
    op.create_index(op.f('ix_rfq_deadline'), 'rfq', ['deadline'], unique=False)
    op.create_index(op.f('ix_rfq_owner'), 'rfq', ['owner'], unique=False)
    op.create_index(op.f('ix_rfq_priority'), 'rfq', ['priority'], unique=False)
    op.create_index(op.f('ix_rfq_rfq_code'), 'rfq', ['rfq_code'], unique=True)
    op.create_index(op.f('ix_rfq_status'), 'rfq', ['status'], unique=False)
    op.create_table('rfq_stage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rfq_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('assigned_team', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('planned_start', sa.Date(), nullable=True),
    sa.Column('planned_end', sa.Date(), nullable=True),
    sa.Column('actual_start', sa.Date(), nullable=True),
    sa.Column('actual_end', sa.Date(), nullable=True),
    sa.Column('blocker_status', sa.String(length=20), nullable=True),
    sa.Column('blocker_reason_code', sa.String(length=100), nullable=True),
    sa.Column('captured_data', sa.JSON(), nullable=True),
    sa.Column('mandatory_fields', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfq.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfq_stage_order'), 'rfq_stage', ['order'], unique=False)
    op.create_index(op.f('ix_rfq_stage_rfq_id'), 'rfq_stage', ['rfq_id'], unique=False)
    if op.get_bind().dialect.name == 'sqlite':
        with op.batch_alter_table('rfq', recreate='always') as batch_op:
            batch_op.create_foreign_key(
                'fk_rfq_current_stage_id_rfq_stage',
                'rfq_stage',
                ['current_stage_id'],
                ['id'],
            )
    else:
        op.create_foreign_key(
            'fk_rfq_current_stage_id_rfq_stage',
            'rfq',
            'rfq_stage',
            ['current_stage_id'],
            ['id'],
        )
    op.create_table('stage_template',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('default_team', sa.String(length=100), nullable=True),
    sa.Column('planned_duration_days', sa.Integer(), nullable=False),
    sa.Column('mandatory_fields', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_template_workflow_id'), 'stage_template', ['workflow_id'], unique=False)
    op.create_table('reminder',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rfq_id', sa.UUID(), nullable=False),
    sa.Column('rfq_stage_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('assigned_to', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('send_count', sa.Integer(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfq.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rfq_stage_id'], ['rfq_stage.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_due_date'), 'reminder', ['due_date'], unique=False)
    op.create_index(op.f('ix_reminder_rfq_id'), 'reminder', ['rfq_id'], unique=False)
    op.create_index(op.f('ix_reminder_status'), 'reminder', ['status'], unique=False)
    op.create_table('rfq_file',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rfq_stage_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_by', sa.String(length=200), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['rfq_stage_id'], ['rfq_stage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfq_file_deleted_at'), 'rfq_file', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_rfq_file_rfq_stage_id'), 'rfq_file', ['rfq_stage_id'], unique=False)
    op.create_table('rfq_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rfq_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(length=200), nullable=True),
    sa.Column('user_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfq.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfq_history_rfq_id'), 'rfq_history', ['rfq_id'], unique=False)
    op.create_table('rfq_note',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rfq_stage_id', sa.UUID(), nullable=False),
    sa.Column('user_name', sa.String(length=200), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['rfq_stage_id'], ['rfq_stage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfq_note_rfq_stage_id'), 'rfq_note', ['rfq_stage_id'], unique=False)
    op.create_table('rfq_stage_field_value',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rfq_stage_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=200), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_by', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['rfq_stage_id'], ['rfq_stage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfq_stage_field_value_rfq_stage_id'), 'rfq_stage_field_value', ['rfq_stage_id'], unique=False)
    op.create_table('subtask',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rfq_stage_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['rfq_stage_id'], ['rfq_stage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtask_deleted_at'), 'subtask', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_subtask_rfq_stage_id'), 'subtask', ['rfq_stage_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subtask_rfq_stage_id'), table_name='subtask')
    op.drop_index(op.f('ix_subtask_deleted_at'), table_name='subtask')
    op.drop_table('subtask')
    op.drop_index(op.f('ix_rfq_stage_field_value_rfq_stage_id'), table_name='rfq_stage_field_value')
    op.drop_table('rfq_stage_field_value')
    op.drop_index(op.f('ix_rfq_note_rfq_stage_id'), table_name='rfq_note')
    op.drop_table('rfq_note')
    op.drop_index(op.f('ix_rfq_history_rfq_id'), table_name='rfq_history')
    op.drop_table('rfq_history')
    op.drop_index(op.f('ix_rfq_file_rfq_stage_id'), table_name='rfq_file')
    op.drop_index(op.f('ix_rfq_file_deleted_at'), table_name='rfq_file')
    op.drop_table('rfq_file')
    op.drop_index(op.f('ix_reminder_status'), table_name='reminder')
    op.drop_index(op.f('ix_reminder_rfq_id'), table_name='reminder')
    op.drop_index(op.f('ix_reminder_due_date'), table_name='reminder')
    op.drop_table('reminder')
    op.drop_index(op.f('ix_stage_template_workflow_id'), table_name='stage_template')
    op.drop_table('stage_template')
    if op.get_bind().dialect.name == 'sqlite':
        with op.batch_alter_table('rfq', recreate='always') as batch_op:
            batch_op.drop_constraint('fk_rfq_current_stage_id_rfq_stage', type_='foreignkey')
    else:
        op.drop_constraint('fk_rfq_current_stage_id_rfq_stage', 'rfq', type_='foreignkey')
    op.drop_index(op.f('ix_rfq_stage_rfq_id'), table_name='rfq_stage')
    op.drop_index(op.f('ix_rfq_stage_order'), table_name='rfq_stage')
    op.drop_table('rfq_stage')
    op.drop_index(op.f('ix_rfq_status'), table_name='rfq')
    op.drop_index(op.f('ix_rfq_rfq_code'), table_name='rfq')
    op.drop_index(op.f('ix_rfq_priority'), table_name='rfq')
    op.drop_index(op.f('ix_rfq_owner'), table_name='rfq')
    op.drop_index(op.f('ix_rfq_deadline'), table_name='rfq')
    op.drop_index(op.f('ix_rfq_current_stage_id'), table_name='rfq')
    op.drop_index(op.f('ix_rfq_created_at'), table_name='rfq')
    op.drop_index(op.f('ix_rfq_client'), table_name='rfq')
    op.drop_table('rfq')
    op.drop_table('workflow')
    op.drop_table('reminder_rule')
    # ### end Alembic commands ###
