from typing import Literal, TypeAlias

RFQ_STATUS_IN_PREPARATION = "In preparation"
RFQ_STATUS_AWARDED = "Awarded"
RFQ_STATUS_LOST = "Lost"
RFQ_STATUS_CANCELLED = "Cancelled"

RfqStatusLiteral: TypeAlias = Literal[
    RFQ_STATUS_IN_PREPARATION,
    RFQ_STATUS_AWARDED,
    RFQ_STATUS_LOST,
    RFQ_STATUS_CANCELLED,
]

RFQ_TERMINAL_STATUSES = frozenset(
    {
        RFQ_STATUS_AWARDED,
        RFQ_STATUS_LOST,
        RFQ_STATUS_CANCELLED,
    }
)

RFQ_ACTIVE_STATUSES = (
    RFQ_STATUS_IN_PREPARATION,
)

RFQ_DECIDED_STATUSES = (
    RFQ_STATUS_AWARDED,
    RFQ_STATUS_LOST,
)

RFQ_OPERATIONAL_STATUSES = (
    RFQ_STATUS_IN_PREPARATION,
    RFQ_STATUS_AWARDED,
    RFQ_STATUS_LOST,
    RFQ_STATUS_CANCELLED,
)

RFQ_VALID_STATUS_TRANSITIONS = {
    RFQ_STATUS_IN_PREPARATION: {
        RFQ_STATUS_AWARDED,
        RFQ_STATUS_LOST,
        RFQ_STATUS_CANCELLED,
    },
    RFQ_STATUS_AWARDED: set(),
    RFQ_STATUS_LOST: set(),
    RFQ_STATUS_CANCELLED: set(),
}
